/*

DKB Raytracer for OS/2 2.0 Presentation Manager
by Michael Caldwell (mcaldwel@netcom.com)

*/


#define ID_MAIN			1
#define ID_FILE			10
#define ID_TRACE			11
#define ID_ABORT			12
#define ID_EXIT			13
#define ID_DISPLAY		20
#define ID_IMAGE			21
#define ID_STATISTICS	22
#define ID_OUTPUT			30
#define ID_TARGA			31
#define ID_DUMP			32
#define ID_RAW				33
#define ID_QUALITY		40
/* these values must be sequential */
#define ID_0				41
#define ID_1				42
#define ID_2				43
#define ID_3				44
#define ID_4				45
#define ID_5				46
#define ID_6				47
#define ID_7				48
#define ID_8				49
#define ID_9				50
/* ------------------------------- */
